package com.app.office.fc.hssf.record.chart;

import com.app.office.fc.hssf.record.RecordInputStream;
import com.app.office.fc.hssf.record.StandardRecord;
import com.app.office.fc.hssf.record.UnknownRecord;
import com.app.office.fc.util.BitField;
import com.app.office.fc.util.BitFieldFactory;
import com.app.office.fc.util.HexDump;
import com.app.office.fc.util.LittleEndian;
import com.app.office.fc.util.LittleEndianOutput;

public final class TextRecord extends StandardRecord {
    public static final short DATA_LABEL_PLACEMENT_ABOVE = 5;
    public static final short DATA_LABEL_PLACEMENT_AUTO = 9;
    public static final short DATA_LABEL_PLACEMENT_AXIS = 4;
    public static final short DATA_LABEL_PLACEMENT_BELOW = 6;
    public static final short DATA_LABEL_PLACEMENT_CENTER = 3;
    public static final short DATA_LABEL_PLACEMENT_CHART_DEPENDENT = 0;
    public static final short DATA_LABEL_PLACEMENT_INSIDE = 2;
    public static final short DATA_LABEL_PLACEMENT_LEFT = 7;
    public static final short DATA_LABEL_PLACEMENT_OUTSIDE = 1;
    public static final short DATA_LABEL_PLACEMENT_RIGHT = 8;
    public static final short DATA_LABEL_PLACEMENT_USER_MOVED = 10;
    public static final short DISPLAY_MODE_OPAQUE = 2;
    public static final short DISPLAY_MODE_TRANSPARENT = 1;
    public static final byte HORIZONTAL_ALIGNMENT_BOTTOM = 3;
    public static final byte HORIZONTAL_ALIGNMENT_CENTER = 2;
    public static final byte HORIZONTAL_ALIGNMENT_JUSTIFY = 4;
    public static final byte HORIZONTAL_ALIGNMENT_LEFT = 1;
    public static final short ROTATION_NONE = 0;
    public static final short ROTATION_ROTATED_90_DEGREES = 2;
    public static final short ROTATION_ROTATED_90_DEGREES_CLOCKWISE = 3;
    public static final short ROTATION_TOP_TO_BOTTOM = 1;
    public static final byte VERTICAL_ALIGNMENT_BOTTOM = 3;
    public static final byte VERTICAL_ALIGNMENT_CENTER = 2;
    public static final byte VERTICAL_ALIGNMENT_JUSTIFY = 4;
    public static final byte VERTICAL_ALIGNMENT_TOP = 1;
    private static final BitField autoBackground = BitFieldFactory.getInstance(128);
    private static final BitField autoColor = BitFieldFactory.getInstance(1);
    private static final BitField autoGeneratedText = BitFieldFactory.getInstance(16);
    private static final BitField autoLabelDeleted = BitFieldFactory.getInstance(64);
    private static final BitField dataLabelPlacement = BitFieldFactory.getInstance(15);
    private static final BitField generated = BitFieldFactory.getInstance(32);
    private static final BitField rotation = BitFieldFactory.getInstance(1792);
    private static final BitField showBubbleSizes = BitFieldFactory.getInstance(8192);
    private static final BitField showCategoryLabelAsPercentage = BitFieldFactory.getInstance(2048);
    private static final BitField showKey = BitFieldFactory.getInstance(2);
    private static final BitField showLabel = BitFieldFactory.getInstance(16384);
    private static final BitField showValue = BitFieldFactory.getInstance(4);
    private static final BitField showValueAsPercentage = BitFieldFactory.getInstance(4096);
    public static final short sid = 4133;
    private static final BitField vertical = BitFieldFactory.getInstance(8);
    private short field_10_indexOfColorValue;
    private short field_11_options2;
    private short field_12_textRotation;
    private byte field_1_horizontalAlignment;
    private byte field_2_verticalAlignment;
    private short field_3_displayMode;
    private int field_4_rgbColor;
    private int field_5_x;
    private int field_6_y;
    private int field_7_width;
    private int field_8_height;
    private short field_9_options1;

    /* access modifiers changed from: protected */
    public int getDataSize() {
        return 32;
    }

    public short getSid() {
        return sid;
    }

    public TextRecord() {
    }

    public TextRecord(UnknownRecord unknownRecord) {
        if (unknownRecord.getSid() == 4133 && unknownRecord.getData().length == getDataSize()) {
            byte[] data = unknownRecord.getData();
            this.field_1_horizontalAlignment = (byte) LittleEndian.getUnsignedByte(data, 0);
            this.field_2_verticalAlignment = (byte) LittleEndian.getUnsignedByte(data, 1);
            this.field_3_displayMode = LittleEndian.getShort(data, 2);
            this.field_4_rgbColor = LittleEndian.getInt(data, 4);
            this.field_5_x = LittleEndian.getInt(data, 8);
            this.field_6_y = LittleEndian.getInt(data, 12);
            this.field_7_width = LittleEndian.getInt(data, 16);
            this.field_8_height = LittleEndian.getInt(data, 20);
            this.field_9_options1 = LittleEndian.getShort(data, 24);
            this.field_10_indexOfColorValue = LittleEndian.getShort(data, 26);
            this.field_11_options2 = LittleEndian.getShort(data, 28);
            this.field_12_textRotation = LittleEndian.getShort(data, 30);
        }
    }

    public TextRecord(RecordInputStream recordInputStream) {
        this.field_1_horizontalAlignment = recordInputStream.readByte();
        this.field_2_verticalAlignment = recordInputStream.readByte();
        this.field_3_displayMode = recordInputStream.readShort();
        this.field_4_rgbColor = recordInputStream.readInt();
        this.field_5_x = recordInputStream.readInt();
        this.field_6_y = recordInputStream.readInt();
        this.field_7_width = recordInputStream.readInt();
        this.field_8_height = recordInputStream.readInt();
        this.field_9_options1 = recordInputStream.readShort();
        this.field_10_indexOfColorValue = recordInputStream.readShort();
        this.field_11_options2 = recordInputStream.readShort();
        this.field_12_textRotation = recordInputStream.readShort();
    }

    public String toString() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("[TEXT]\n");
        stringBuffer.append("    .horizontalAlignment  = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getHorizontalAlignment()));
        stringBuffer.append(" (");
        stringBuffer.append(getHorizontalAlignment());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .verticalAlignment    = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getVerticalAlignment()));
        stringBuffer.append(" (");
        stringBuffer.append(getVerticalAlignment());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .displayMode          = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getDisplayMode()));
        stringBuffer.append(" (");
        stringBuffer.append(getDisplayMode());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .rgbColor             = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getRgbColor()));
        stringBuffer.append(" (");
        stringBuffer.append(getRgbColor());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .x                    = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getX()));
        stringBuffer.append(" (");
        stringBuffer.append(getX());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .y                    = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getY()));
        stringBuffer.append(" (");
        stringBuffer.append(getY());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .width                = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getWidth()));
        stringBuffer.append(" (");
        stringBuffer.append(getWidth());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .height               = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getHeight()));
        stringBuffer.append(" (");
        stringBuffer.append(getHeight());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .options1             = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getOptions1()));
        stringBuffer.append(" (");
        stringBuffer.append(getOptions1());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("         .autoColor                = ");
        stringBuffer.append(isAutoColor());
        stringBuffer.append(10);
        stringBuffer.append("         .showKey                  = ");
        stringBuffer.append(isShowKey());
        stringBuffer.append(10);
        stringBuffer.append("         .showValue                = ");
        stringBuffer.append(isShowValue());
        stringBuffer.append(10);
        stringBuffer.append("         .vertical                 = ");
        stringBuffer.append(isVertical());
        stringBuffer.append(10);
        stringBuffer.append("         .autoGeneratedText        = ");
        stringBuffer.append(isAutoGeneratedText());
        stringBuffer.append(10);
        stringBuffer.append("         .generated                = ");
        stringBuffer.append(isGenerated());
        stringBuffer.append(10);
        stringBuffer.append("         .autoLabelDeleted         = ");
        stringBuffer.append(isAutoLabelDeleted());
        stringBuffer.append(10);
        stringBuffer.append("         .autoBackground           = ");
        stringBuffer.append(isAutoBackground());
        stringBuffer.append(10);
        stringBuffer.append("         .rotation                 = ");
        stringBuffer.append(getRotation());
        stringBuffer.append(10);
        stringBuffer.append("         .showCategoryLabelAsPercentage     = ");
        stringBuffer.append(isShowCategoryLabelAsPercentage());
        stringBuffer.append(10);
        stringBuffer.append("         .showValueAsPercentage     = ");
        stringBuffer.append(isShowValueAsPercentage());
        stringBuffer.append(10);
        stringBuffer.append("         .showBubbleSizes          = ");
        stringBuffer.append(isShowBubbleSizes());
        stringBuffer.append(10);
        stringBuffer.append("         .showLabel                = ");
        stringBuffer.append(isShowLabel());
        stringBuffer.append(10);
        stringBuffer.append("    .indexOfColorValue    = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getIndexOfColorValue()));
        stringBuffer.append(" (");
        stringBuffer.append(getIndexOfColorValue());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("    .options2             = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getOptions2()));
        stringBuffer.append(" (");
        stringBuffer.append(getOptions2());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("         .dataLabelPlacement       = ");
        stringBuffer.append(getDataLabelPlacement());
        stringBuffer.append(10);
        stringBuffer.append("    .textRotation         = ");
        stringBuffer.append("0x");
        stringBuffer.append(HexDump.toHex(getTextRotation()));
        stringBuffer.append(" (");
        stringBuffer.append(getTextRotation());
        stringBuffer.append(" )");
        stringBuffer.append(System.getProperty("line.separator"));
        stringBuffer.append("[/TEXT]\n");
        return stringBuffer.toString();
    }

    public void serialize(LittleEndianOutput littleEndianOutput) {
        littleEndianOutput.writeByte(this.field_1_horizontalAlignment);
        littleEndianOutput.writeByte(this.field_2_verticalAlignment);
        littleEndianOutput.writeShort(this.field_3_displayMode);
        littleEndianOutput.writeInt(this.field_4_rgbColor);
        littleEndianOutput.writeInt(this.field_5_x);
        littleEndianOutput.writeInt(this.field_6_y);
        littleEndianOutput.writeInt(this.field_7_width);
        littleEndianOutput.writeInt(this.field_8_height);
        littleEndianOutput.writeShort(this.field_9_options1);
        littleEndianOutput.writeShort(this.field_10_indexOfColorValue);
        littleEndianOutput.writeShort(this.field_11_options2);
        littleEndianOutput.writeShort(this.field_12_textRotation);
    }

    public Object clone() {
        TextRecord textRecord = new TextRecord();
        textRecord.field_1_horizontalAlignment = this.field_1_horizontalAlignment;
        textRecord.field_2_verticalAlignment = this.field_2_verticalAlignment;
        textRecord.field_3_displayMode = this.field_3_displayMode;
        textRecord.field_4_rgbColor = this.field_4_rgbColor;
        textRecord.field_5_x = this.field_5_x;
        textRecord.field_6_y = this.field_6_y;
        textRecord.field_7_width = this.field_7_width;
        textRecord.field_8_height = this.field_8_height;
        textRecord.field_9_options1 = this.field_9_options1;
        textRecord.field_10_indexOfColorValue = this.field_10_indexOfColorValue;
        textRecord.field_11_options2 = this.field_11_options2;
        textRecord.field_12_textRotation = this.field_12_textRotation;
        return textRecord;
    }

    public byte getHorizontalAlignment() {
        return this.field_1_horizontalAlignment;
    }

    public void setHorizontalAlignment(byte b) {
        this.field_1_horizontalAlignment = b;
    }

    public byte getVerticalAlignment() {
        return this.field_2_verticalAlignment;
    }

    public void setVerticalAlignment(byte b) {
        this.field_2_verticalAlignment = b;
    }

    public short getDisplayMode() {
        return this.field_3_displayMode;
    }

    public void setDisplayMode(short s) {
        this.field_3_displayMode = s;
    }

    public int getRgbColor() {
        return this.field_4_rgbColor;
    }

    public void setRgbColor(int i) {
        this.field_4_rgbColor = i;
    }

    public int getX() {
        return this.field_5_x;
    }

    public void setX(int i) {
        this.field_5_x = i;
    }

    public int getY() {
        return this.field_6_y;
    }

    public void setY(int i) {
        this.field_6_y = i;
    }

    public int getWidth() {
        return this.field_7_width;
    }

    public void setWidth(int i) {
        this.field_7_width = i;
    }

    public int getHeight() {
        return this.field_8_height;
    }

    public void setHeight(int i) {
        this.field_8_height = i;
    }

    public short getOptions1() {
        return this.field_9_options1;
    }

    public void setOptions1(short s) {
        this.field_9_options1 = s;
    }

    public short getIndexOfColorValue() {
        return this.field_10_indexOfColorValue;
    }

    public void setIndexOfColorValue(short s) {
        this.field_10_indexOfColorValue = s;
    }

    public short getOptions2() {
        return this.field_11_options2;
    }

    public void setOptions2(short s) {
        this.field_11_options2 = s;
    }

    public short getTextRotation() {
        return this.field_12_textRotation;
    }

    public void setTextRotation(short s) {
        this.field_12_textRotation = s;
    }

    public void setAutoColor(boolean z) {
        this.field_9_options1 = autoColor.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoColor() {
        return autoColor.isSet(this.field_9_options1);
    }

    public void setShowKey(boolean z) {
        this.field_9_options1 = showKey.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowKey() {
        return showKey.isSet(this.field_9_options1);
    }

    public void setShowValue(boolean z) {
        this.field_9_options1 = showValue.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowValue() {
        return showValue.isSet(this.field_9_options1);
    }

    public void setVertical(boolean z) {
        this.field_9_options1 = vertical.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isVertical() {
        return vertical.isSet(this.field_9_options1);
    }

    public void setAutoGeneratedText(boolean z) {
        this.field_9_options1 = autoGeneratedText.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoGeneratedText() {
        return autoGeneratedText.isSet(this.field_9_options1);
    }

    public void setGenerated(boolean z) {
        this.field_9_options1 = generated.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isGenerated() {
        return generated.isSet(this.field_9_options1);
    }

    public void setAutoLabelDeleted(boolean z) {
        this.field_9_options1 = autoLabelDeleted.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoLabelDeleted() {
        return autoLabelDeleted.isSet(this.field_9_options1);
    }

    public void setAutoBackground(boolean z) {
        this.field_9_options1 = autoBackground.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isAutoBackground() {
        return autoBackground.isSet(this.field_9_options1);
    }

    public void setRotation(short s) {
        this.field_9_options1 = rotation.setShortValue(this.field_9_options1, s);
    }

    public short getRotation() {
        return rotation.getShortValue(this.field_9_options1);
    }

    public void setShowCategoryLabelAsPercentage(boolean z) {
        this.field_9_options1 = showCategoryLabelAsPercentage.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowCategoryLabelAsPercentage() {
        return showCategoryLabelAsPercentage.isSet(this.field_9_options1);
    }

    public void setShowValueAsPercentage(boolean z) {
        this.field_9_options1 = showValueAsPercentage.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowValueAsPercentage() {
        return showValueAsPercentage.isSet(this.field_9_options1);
    }

    public void setShowBubbleSizes(boolean z) {
        this.field_9_options1 = showBubbleSizes.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowBubbleSizes() {
        return showBubbleSizes.isSet(this.field_9_options1);
    }

    public void setShowLabel(boolean z) {
        this.field_9_options1 = showLabel.setShortBoolean(this.field_9_options1, z);
    }

    public boolean isShowLabel() {
        return showLabel.isSet(this.field_9_options1);
    }

    public void setDataLabelPlacement(short s) {
        this.field_11_options2 = dataLabelPlacement.setShortValue(this.field_11_options2, s);
    }

    public short getDataLabelPlacement() {
        return dataLabelPlacement.getShortValue(this.field_11_options2);
    }
}
